const sfx = {
  paths: [
    { path: "./sfx/ui/menu_select.mp3" },
    { path: "./sfx/ui/menu_hover.mp3" },
    { path: "./sfx/ui/menu_error.mp3" },
    { path: "./sfx/spells/thunderfx0.mp3" },
    { path: "./sfx/spells/thunderfx1.mp3" },
    { path: "./sfx/spells/thunderfx2.mp3" },
    { path: "./sfx/spells/thunderfx3.mp3" },
    { path: "./sfx/skeletons/skeleton_hit.mp3" },
    { path: "./sfx/skeletons/skeleton_crit.mp3" },
    { path: "./sfx/knight/woosh.mp3" },
    { path: "./sfx/knight/running_grass.mp3" },
    { path: "./sfx/general/swish1.mp3" },
    { path: "./sfx/general/swish2.mp3" },
    { path: "./sfx/general/hurt_sound.mp3" },
    { path: "./sfx/dialogue/text.wav" },
  ],
  menu_select: { path: "./sfx/ui/menu_select.mp3", volume: 0.8 },
  menu_hover: { path: "./sfx/ui/menu_hover.mp3", volume: 0.4 },
  menu_error: { path: "./sfx/ui/menu_error.mp3", volume: 0.4 },
  thunderfx0: { path: "./sfx/spells/thunderfx0.mp3", volume: 0.12 },
  thunderfx1: { path: "./sfx/spells/thunderfx1.mp3", volume: 0.12 },
  thunderfx2: { path: "./sfx/spells/thunderfx2.mp3", volume: 0.12 },
  thunderfx3: { path: "./sfx/spells/thunderfx3.mp3", volume: 0.12 },
  skeleton_hit: { path: "./sfx/skeletons/skeleton_hit.mp3", volume: 0.18 },
  skeleton_crit: { path: "./sfx/skeletons/skeleton_crit.mp3", volume: 0.17 },
  dash: { path: "./sfx/knight/woosh.mp3", volume: 0.7 },
  running: { path: "./sfx/knight/running_grass.mp3", volume: 0.3 },
  swish1: { path: "./sfx/general/swish1.mp3", volume: 0.35 },
  swish2: { path: "./sfx/general/swish2.mp3", volume: 0.35 },
  hurt_sound: { path: "./sfx/general/hurt_sound.mp3", volume: 0.15 },
  text: { path: "./sfx/dialogue/text.wav", volume: 0.7 },
};
