const sprites = {
  paths: [
    { path: "./sprites/overlays/vignette.png" },
    { path: "./sprites/map/level_1/props/teleporter.png" },
    { path: "./sprites/map/level_1/props/shop.png" },
    { path: "./sprites/map/level_1/props/props.png" },
    { path: "./sprites/map/level_1/props/prop_shadows.png" },
    { path: "./sprites/map/level_1/props/foilage.png" },
    { path: "./sprites/map/level_1/props/foilage_shadows.png" },
    { path: "./sprites/map/level_1/level/level_1.png" },
    { path: "./sprites/map/level_1/bossroom/level_1_bossroom.png" },
    { path: "./sprites/items/shop_items.png" },
    { path: "./sprites/items/drop_items.png" },
    { path: "./sprites/hud/shield.png" },
    { path: "./sprites/hud/icons.png" },
    { path: "./sprites/hud/cursor.png" },
    { path: "./sprites/homescreen/homescreen.png" },
    { path: "./sprites/entities/vfx/spawn_vfx.png" },
    { path: "./sprites/entities/spells/thunder_spell.png" },
    { path: "./sprites/entities/knight/knight.png" },
    { path: "./sprites/entities/knight/knight_dash.png" },
    { path: "./sprites/entities/enemies/skeleton.png" },
    { path: "./sprites/entities/enemies/minion.png" },
    { path: "./sprites/entities/bosses/minotaur.png" },
    { path: "./sprites/controls/ui/back.png" },
    { path: "./sprites/controls/keys/w.png" },
    { path: "./sprites/controls/keys/tab.png" },
    { path: "./sprites/controls/keys/space.png" },
    { path: "./sprites/controls/keys/s.png" },
    { path: "./sprites/controls/keys/e.png" },
    { path: "./sprites/controls/keys/d.png" },
    { path: "./sprites/controls/keys/a.png" },
  ],
  vignette: "./sprites/overlays/vignette.png",
  teleporter: "./sprites/map/level_1/props/teleporter.png",
  shop: "./sprites/map/level_1/props/shop.png",
  props: "./sprites/map/level_1/props/props.png",
  prop_shadows: "./sprites/map/level_1/props/prop_shadows.png",
  foilage: "./sprites/map/level_1/props/foilage.png",
  foilage_shadows: "./sprites/map/level_1/props/foilage_shadows.png",
  level1: "./sprites/map/level_1/level/level_1.png",
  level1_bossroom: "./sprites/map/level_1/bossroom/level_1_bossroom.png",
  shop_items: "./sprites/items/shop_items.png",
  drop_items: "./sprites/items/drop_items.png",
  shield: "./sprites/hud/shield.png",
  icons: "./sprites/hud/icons.png",
  cursor: "./sprites/hud/cursor.png",
  homescreen: "./sprites/homescreen/homescreen.png",
  spawn_vfx: "./sprites/entities/vfx/spawn_vfx.png",
  thunder_spell: "./sprites/entities/spells/thunder_spell.png",
  knight: "./sprites/entities/knight/knight.png",
  knight_dash: "./sprites/entities/knight/knight_dash.png",
  skeleton: "./sprites/entities/enemies/skeleton.png",
  minion: "./sprites/entities/enemies/minion.png",
  minotaur: "./sprites/entities/bosses/minotaur.png",
  back_button: "./sprites/controls/ui/back.png",
  w_key: "./sprites/controls/keys/w.png",
  s_key: "./sprites/controls/keys/s.png",
  e_key: "./sprites/controls/keys/e.png",
  d_key: "./sprites/controls/keys/d.png",
  a_key: "./sprites/controls/keys/a.png",
  tab_key: "./sprites/controls/keys/tab.png",
  space_key: "./sprites/controls/keys/space.png",
};
